-- Auto-generated by tidc_scoring.py
-- Fund: DUX Receivables Fund I (tidc_dux_001)
-- Generated: 2026-03-19 14:02:33
-- Creative economy factoring — TIDC risk scores + monthly aggregates

-- Risk score (upsert)
INSERT INTO risk_tidc_scores (pipeline_key, reference_date, score_risco, faixa_risco, alerta_deterioracao, confidence_tier, confidence_label, collection_rate, default_ratio, overdue_ratio, on_time_payment_ratio, distance_to_loss, expected_loss_proxy, effective_yield, mean_monthly_yield, sacado_top5_pct, cedente_top5_pct, n_months_total)
VALUES ('tidc_dux_001', '2026-03-19', 0.624089, 'Alto', TRUE, 2, 'Medium (12-23 months)', 0.782123, 0.061431, 0.098997, 0.753754, 0.874396, 0.048096, 5.500966, 6.669068, 0.420107, 0.307051, 12)
ON CONFLICT (pipeline_key) DO UPDATE SET
    reference_date = EXCLUDED.reference_date,
    score_risco = EXCLUDED.score_risco,
    faixa_risco = EXCLUDED.faixa_risco,
    alerta_deterioracao = EXCLUDED.alerta_deterioracao,
    confidence_tier = EXCLUDED.confidence_tier,
    confidence_label = EXCLUDED.confidence_label,
    collection_rate = EXCLUDED.collection_rate,
    default_ratio = EXCLUDED.default_ratio,
    overdue_ratio = EXCLUDED.overdue_ratio,
    on_time_payment_ratio = EXCLUDED.on_time_payment_ratio,
    distance_to_loss = EXCLUDED.distance_to_loss,
    expected_loss_proxy = EXCLUDED.expected_loss_proxy,
    effective_yield = EXCLUDED.effective_yield,
    mean_monthly_yield = EXCLUDED.mean_monthly_yield,
    sacado_top5_pct = EXCLUDED.sacado_top5_pct,
    cedente_top5_pct = EXCLUDED.cedente_top5_pct,
    n_months_total = EXCLUDED.n_months_total;

-- Monthly risk aggregates (12 rows)
-- Clear existing TIDC monthly risk data
DELETE FROM risk_tidc_monthly WHERE pipeline_key = 'tidc_dux_001';

INSERT INTO risk_tidc_monthly (pipeline_key, reference_month, total_items, total_face_value, total_acquisition_value, avg_discount_rate, effective_yield, advance_rate, sacado_effective_n, sacado_top5_pct, cedente_effective_n, cedente_top5_pct, collection_rate, overdue_ratio, default_ratio, inad_early_ratio, inad_mid_ratio, inad_severe_ratio, wal_days, on_time_payment_ratio, distance_to_loss)
VALUES
  ('tidc_dux_001', '2025-04-01', 20, 275194.390000, 254827.080000, 3.904500, 7.992600, 0.925989, 4.653628, 0.877275, 7.693541, 0.731937, 0.000000, 1.000000, 0.000000, 0.107739, 0.000000, 0.000000, 51.587887, 0.000000, 0.816921),
  ('tidc_dux_001', '2025-05-01', 20, 219268.570000, 205120.250000, 3.787500, 6.897573, 0.935475, 8.423183, 0.655429, 12.667021, 0.552469, 0.476567, 0.355174, 0.156022, 0.044760, 0.101893, 0.000000, 37.935160, 0.600000, 0.853348),
  ('tidc_dux_001', '2025-06-01', 20, 216954.030000, 205623.660000, 3.361500, 5.510246, 0.947775, 10.243759, 0.604434, 13.559929, 0.506667, 0.696270, 0.215990, 0.081359, 0.011770, 0.101929, 0.000000, 28.769599, 0.761905, 0.886301),
  ('tidc_dux_001', '2025-07-01', 30, 377802.270000, 353133.840000, 3.565333, 6.985575, 0.934705, 11.326747, 0.542944, 15.523959, 0.454937, 0.834139, 0.124199, 0.038632, 0.011382, 0.028007, 0.046255, 37.768732, 0.840909, 0.914356),
  ('tidc_dux_001', '2025-08-01', 30, 487429.050000, 454389.650000, 3.517667, 7.271160, 0.932217, 11.252525, 0.583365, 19.162761, 0.401331, 0.810723, 0.141042, 0.046048, 0.034995, 0.013174, 0.045993, 34.354636, 0.814286, 0.905838),
  ('tidc_dux_001', '2025-09-01', 30, 715373.290000, 667878.210000, 3.769667, 7.111338, 0.933608, 12.319733, 0.511476, 19.508825, 0.394748, 0.739778, 0.122433, 0.136327, 0.031395, 0.029482, 0.035291, 35.325662, 0.817204, 0.866007),
  ('tidc_dux_001', '2025-10-01', 40, 607236.850000, 571331.600000, 3.474250, 6.284485, 0.940871, 13.035136, 0.486730, 21.626287, 0.356185, 0.806469, 0.089029, 0.097165, 0.005382, 0.073754, 0.032175, 31.256524, 0.838462, 0.888689),
  ('tidc_dux_001', '2025-11-01', 40, 585448.550000, 552621.330000, 3.421500, 5.940274, 0.943928, 13.392208, 0.469458, 21.489127, 0.350261, 0.775934, 0.118016, 0.099939, 0.062978, 0.050007, 0.042603, 29.653781, 0.821429, 0.844412),
  ('tidc_dux_001', '2025-12-01', 40, 561103.320000, 524582.240000, 3.661500, 6.961936, 0.934912, 13.988161, 0.436031, 23.277984, 0.311267, 0.791268, 0.120642, 0.081566, 0.021048, 0.058100, 0.075910, 32.908860, 0.825243, 0.844943),
  ('tidc_dux_001', '2026-01-01', 50, 832270.530000, 774856.100000, 3.664400, 7.409689, 0.931015, 13.610031, 0.453274, 23.959847, 0.316670, 0.797496, 0.117446, 0.079023, 0.019356, 0.061243, 0.067359, 35.222970, 0.819672, 0.852042),
  ('tidc_dux_001', '2026-02-01', 50, 821319.960000, 773640.670000, 3.492600, 6.162976, 0.941948, 14.042288, 0.433617, 24.157456, 0.307902, 0.800770, 0.117620, 0.075557, 0.013195, 0.031508, 0.095129, 28.037092, 0.812274, 0.860168),
  ('tidc_dux_001', '2026-03-01', 50, 781698.270000, 740939.440000, 3.228400, 5.500966, 0.947859, 14.273221, 0.420107, 24.179075, 0.307051, 0.782123, 0.098997, 0.061431, 0.002637, 0.026172, 0.096794, 31.076790, 0.753754, 0.874396);
